config/routes.rb
Rails.application.routes.draw do
  get 'drink/index'

  resources :contacts

  get 'gallery/index'

  get 'functions' => 'functions#index'

  get 'book' => 'book#index'

  get 'menu' => 'menu#index'

  get 'about' => 'about#index'

  get 'gallery' => 'gallery#index'

  get 'functions' => 'functions#index'

  get 'drink' => 'drink#index'

  get 'home/index'

  get 'menu_download' => 'menu#download'

  get 'menu_lunch' => 'menu#download_lunch'

  get 'menu_kids' => 'menu#download_kids'

  get 'menu_drinks' => 'drink#download_drinks'

  get 'functions_pdf' => 'functions#download'

  root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessor :hidden_field
  
  validates :name, :presence => true
  validates :message, :presence => true
  validates :phone, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  # we are actually creating new contact entries from the index. There will be now view of these contacts anywhere.
  def index
    @contact = Contact.new
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  # create a new contact entry in the database. Send these details to the ContactMailer.
  def create
    @contact = Contact.new(contact_params)

    unless @contact.hidden_field.blank?
      redirect_to new_contact_path, notice: 'Message not sent - suspicious data submitted. Please try again.'
      return
    end

    if @contact.save
      ContactMailer.contact_email(@contact).deliver_now
      redirect_to new_contact_path, notice: 'Your message has been successfully sent.'
    else
      redirect_to new_contact_path, notice: 'Sorry there has been a problem sending this message'
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :date, :message, :hidden_field)
    end
end

app/controllers/drink_controller.rb
class DrinkController < ApplicationController
  def index
  end

  def download_drinks
    send_file(
      "#{Rails.root}/public/WoodenHorseDrinksMenu.pdf",
      filename: "WoodenHorseDrinksMenu.pdf",
      type: "application/pdf"
    )
  end

end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  def index
  end

  def download
    send_file(
      "#{Rails.root}/public/Wooden Horse Restaurant Function Information.pdf",
      filename: "Wooden Horse Restaurant Function Information.pdf",
      type: "application/pdf"
    )
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end

  def download
    send_file(
      "#{Rails.root}/public/WoodenHorseMenu.pdf",
      filename: "WoodenHorseMenu.pdf",
      type: "application/pdf"
    )
  end

  def download_kids
    send_file(
      "#{Rails.root}/public/WoodenHorseKidsMenu.pdf",
      filename: "WoodenHorseKidsMenu.pdf",
      type: "application/pdf"
    )
  end

  def download_lunch
    send_file(
      "#{Rails.root}/public/Lunch at Wooden Horse.pdf",
      filename: "Lunch at Wooden Horse.pdf",
      type: "application/pdf"
    )
  end

 end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/drink_helper.rb
module DrinkHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact, url: contacts_path, html: { multipart: true, method: :post} ) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this enquiry from being sent:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-lg-4">
      <label>Name</label>
      <%= f.input_field :name, :required => true, class: 'form-control', style: 'padding-top:1px;padding-bottom:1px;line-height:30px;' %>
    </div>
    <div class="form-group col-lg-4">
      <label>Email Address</label>
      <%= f.input_field :email, class: 'form-control', style: 'padding-top:1px;padding-bottom:1px;line-height:30px;' %>
    </div>
    <div class="form-group col-lg-4">
      <label>Phone Number</label>
      <%= f.input_field :phone, as: :string, :required => true, class: 'form-control', style: 'padding-top:1px;padding-bottom:1px;line-height:30px;' %>
    </div>
    <div class="clearfix"></div>
    <div class="form-group col-lg-12">
      <label>Message</label>
      <%= f.input_field :message, as: :text, class: 'form-control', style: 'padding-top:1px;padding-bottom:1px;line-height:30px;', input_html: {rows: 4, required: true} %>
    </div>
    <%= f.input_field :hidden_field, id: 'bot', style: 'display:none;' %>

    <%= f.submit 'Send the Message', class: 'btn btn-primary', style: 'margin-left:15px;line-height:20px;padding-top:3px;' %>
  </div>
      
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Date:</strong>
  <%= @contact.date %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/drink/index.html.erb
<div class="container">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center">Our Drinks Menu</h2>
        <hr>
        <div class="table-responsive">
          <table class="table">
            <tr>
              <th style="width:70%">Wine by the Bottle</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%"><i>Sparkling</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">Redbank Ellora Vintage Chardonnay Pinot Noir`13, King Valley VIC</td>
              <td>$50</td>
            </tr>
            <tr>
              <td style="width:70%">Cester Dasogno Prosecco NV, ITY</td>
              <td>$53</td>
            </tr>
            <tr>
              <td style="width:70%">Deviation Road Altair Sparkling Rose NV, Adelaide Hills SA</td>
              <td>$65</td>
            </tr>
            <tr>
              <td style="width:70%">Pol Roger Brut Reserve NV, FRA</td>
              <td>$130</td>
            </tr>
            <tr>
              <td style="width:70%"><i>White</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">Chaffey Bros. Not your Grandma’s Riesling `15, Eden Valley SA</td>
              <td>$50</td>
            </tr>
            <tr>
              <td style="width:70%">Critteden Estate, Pinocchio Pinot Grigio `15, Mornington Peninsula VIC</td>
              <td>$60</td>
            </tr>
            <tr>
              <td style="width:70%">Collefrisio Vignaquadra Pecorino `15,Abruzzo ITY </td>
              <td>$45</td>
            </tr>
            <tr>
              <td style="width:70%">Hugel Et Fils Pinot Blanc `13, Alsace FRA</td>
              <td>$52</td>
            </tr>
            <tr>
              <td style="width:70%">Greywacke Sauvignon Blanc `14, Marlborough NZ</td>
              <td>$58</td>
            </tr>
            <tr>
              <td style="width:70%">Livon Braide Alte Gran Cru `11, Udine ITA</td>
              <td>$120</td>
            </tr>
            <tr>
              <td style="width:70%">Pala i Fiori Vermentino Di Sardegna `15, ITY</td>
              <td>$45</td>
            </tr>
            <tr>
              <td style="width:70%">Hill-Smith Estate Chardonnay `15, Adelaide Hills SA</td>
              <td>$63</td>
            </tr>
            <tr>
              <td style="width:70%">Terra di Granito Viognier `14, Granite Belt QLD</td>
              <td>$50</td>
            </tr>
            <tr>
              <td style="width:70%"><i>Rose</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">Langmeil Bella Rouge Rose `15, Barossa SA</td>
              <td>$45</td>
            </tr>
            <tr>
              <td style="width:70%">Chateau de L'Aumerade Marie Christine Rose `14, Provence FRA</td>
              <td>$72</td>
            </tr>
            <tr>
              <td style="width:70%"><i>Red</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">Santuario Malbec/Shiraz `14, Mendoza ARG</td>
              <td>$50</td>
            </tr>
            <tr>
              <td style="width:70%">Heathcote Cravens Place Shiraz `15, Heathcote VIC</td>
              <td>$54</td>
            </tr>
            <tr>
              <td style="width:70%">Yalumba ‘The Octavius’ Old Vine Shiraz `12, Barossa, SA</td>
              <td>$130</td>
            </tr>
            <tr>
              <td style="width:70%">Rob Hall Cabernet `15, Yarra Valley VIC</td>
              <td>$60</td>
            </tr>
            <tr>
              <td style="width:70%">Bleasdale ‘The Iron Duke’ Cabernet Sauvignon `12, Langhorne Creek, SA</td>
              <td>$115</td>
            </tr>
            <tr>
              <td style="width:70%">Crittenden Estate `14, Geppetto Pinot Noir, MP VIC</td>
              <td>$62</td>
            </tr>
            <tr>
              <td style="width:70%">Jericho GSM `15, McLaren Vale, SA</td>
              <td>$46</td>
            </tr>
            <tr>
              <td style="width:70%">Torres Ibericos Alta Rioja `12, Penedes ESP</td>
              <td>$49</td>
            </tr>
            <tr>
              <td style="width:70%">Lunaria Coste di moro Montepulciano `12, Abruzzo ITA</td>
              <td>$75</td>
            </tr>
            <tr>
              <td style="width:70%">Chateau Musar Jeune Red `12, Bekka Valley LEB</td>
              <td>$62</td>
            </tr>
            <tr>
              <td style="width:70%">Donatella Cinelli Colombini Brunello Sangiovese `07, Tuscany ITA</td>
              <td>$185</td>
            </tr>
          </table>
        </div>
        </br>
        <div class="table-responsive">
          <table class="table">
            <tr>
              <th style="width:70%">Cocktails</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%">Two of Us</br>golden rum | lime | mint | grapefruit bitters | ginger</td>
              <td>$28 ~ to share</td>
            </tr>
            <tr>
              <td style="width:70%">Lucy in the Sky With Diamonds</br>vodka | apricot brandy | rose | lemon | pineapple | pistachio dust</td>
              <td>$16</td>
            </tr>
            <tr>
              <td style="width:70%">Day Tripper</br>tequila | triple sec | watermelon | lime |agave | salt</td>
              <td>$16</td>
            </tr>
            <tr>
              <td style="width:70%">Dizzy Miss Lizzy</br>gin | lime | mint | gomme</td>
              <td>$16</td>
            </tr>
            <tr>
              <td style="width:70%">Long Tall Sally</br>gin | peach liqueur | campari | passionfruit | lemon | gomme</td>
              <td>$16</td>
            </tr>
            <tr>
              <td style="width:70%">A Hard Day’s Night</br>bourbon whiskey | elderflower | apple | bitters | burnt rosemary</td>
              <td>$18</td>
            </tr>
            <tr>
              <td style="width:70%">Savoy Truffle</br>spiced rum | kahlua | espresso | maple syrup |chocolate bitters</td>
              <td>$18</td>
            </tr>
          </table>
        </div>
        </br>
        <div class="table-responsive">
          <table class="table">
            <tr>
              <th style="width:70%">The Bar Fridge</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%"><i>Lager</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">Coopers Premium Light</td>
              <td>$6</td>
            </tr>
            <tr>
              <td style="width:70%">East 9th  Doss Blockos Pale Lager </td>
              <td>$8</td>
            </tr>
            <tr>
              <td style="width:70%">Stone & Wood Green Coast Lager</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Enigma Pilsner</td>
              <td>$10</td>
            </tr>
            <tr>
              <td style="width:70%"><i>Wheat Beer</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">4 Pines Hefeweizen</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Feral White</td>
              <td>$11</td>
            </tr>
            <tr>
              <td style="width:70%"><i>Ale</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">Newstead ‘3 Quarter Time’ Session Ale</td>
              <td>$8</td>
            </tr>
            <tr>
              <td style="width:70%">Riverside 69 Summer Ale</td>
              <td>$10</td>
            </tr>
            <tr>
              <td style="width:70%">Cricketers Spearhead Pale Ale</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">4 Pines Pale Ale</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Mountain Goat ‘Hightail’ Amber Ale</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Newstead Two to the Valley IPA</td>
              <td>$10</td>
            </tr>
            <tr>
              <td style="width:70%"><i>Cider & Speciality Beers</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">East 9  Lick Pier Ginger Beer</td>
              <td>$12</td>
            </tr>
            <tr>
              <td style="width:70%">Napoleone & Co. Pear Cider</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Batlow Cloudy Apple Cider</td>
              <td>$11</td>
            </tr>
            <tr>
              <td style="width:70%"><i>Bitters & Dark Beers</i></td>
              <td></td>
            </tr>
            <tr>
              <td style="width:70%">Burleigh My Wife’s Bitter</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Riverside 88 Robust Porter</td>
              <td>$12</td>
            </tr>
          </table>
        </div>
        </br>
        <p><i>Rotational craft beers available on tap. Alternative wines available by the glass. Download our complete drinks menu to see the details.</i></p>
        <%= link_to 'Drinks Menu (PDF)', menu_drinks_url, class: "btn btn-secondary btn-lg", style: "font-style:italic", alt: "", align: "right" %>
      </div>
    </div>
  </div>
</div>

app/views/menu/index.html.erb
<div class="container">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center">Our Food Menu</h2>
        <hr>
        <div class="table-responsive">
          <table class="table">
            <tr>
              <th style="width:70%">Entrees / Share Plates</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%">MARKET OYSTERS ‘shucked to order’</br>pomegranate, chardonnay verjus</td>
              <td>$3.5ea</td>
            </tr>
            <tr>
              <td style="width:70%">HOUSE BAKED PANE SCIOCCO</br>‘bee one third’ honey, smoked butter, burnt vanilla</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">HINTERLAND ZUCCHINI FLOWERS</br>scamorza, caramelised onion, harissa</td>
              <td>$6ea</td>
            </tr>
            <tr>
              <td style="width:70%">DEVILLED BEEF CROQUETAS</br>air-dried wagyu, egg, green goddess sauce</td>
              <td>$13</td>
            </tr>
            <tr>
              <td style="width:70%">DUCK LIVER PARFAIT</br>PX jelly, house pickle, truffle snow, torn bread</td>
              <td>$17</td>
            </tr>
            <tr>
              <td style="width:70%">THE WOODEN MEAT BOARD #6</br>smoked brisket pastrami, chilli & fennel lonza, spreadable pig, squid ink grissini, aged rosemary rind manchego, wild olives, house pickles</td>
              <td>$22</td>
            </tr>
          </table>
          </br>
          <table class="table">
            <tr>
              <th style="width:70%">Main</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%">SLOW & STEADY PIG</br>32 hour shoulder steak, smoke & flame, pan seared scallops, grape, scratchings, enidve, pig sauce</td>
              <td>$37</td>
            </tr>
            <tr>
              <td style="width:70%">SPICED PUMPKIN & FETA AGNOLOTTI</br>honey walnut, wilted spinach, burnt garlic & marjoram butter, cured egg yolk, aged parmesan</td>
              <td>$34</td>
            </tr>
            <tr>
              <td style="width:70%">PAN SEARED NZ KING SALMON</br>spanner crab broth, chorizo, kinkawooka mussels, tomato,basil,saffronrouille</td>
              <td>$36</td>
            </tr>
            <tr>
              <td style="width:70%">LOW FLYING BIRD</br>BBQ chicken maryland, North African spice, shaved cucumber, pomegranate, smoked goat’s cheese, almond, dill</td>
              <td>$35</td>
            </tr>
            <tr>
              <td style="width:70%">ROO W COFFEE</br>medium rare kangaroo loin, Jerusalem artichoke, fig, coffee butter, warrigal greens, cherry, jus</td>
              <td>$40</td>
            </tr>
            <tr>
              <td style="width:70%">300G KOBE SCORE 9+ RUMP</br>smoke & flame, Italian slaw, porcini salted shoestring, gentlemen’s relish, veal bone jus</td>
              <td>$50</td>
            </tr>
          </table>
          </br>
          <table class="table">
            <tr>
              <th style="width:70%">Sides</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%">porcini salted shoestring fries, confit garlic mayo</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Italian slaw, raisin, parmesan, crouton</td>
              <td>$8</td>
            </tr>
            <tr>
              <td style="width:70%">shaved cucumber, pomegranate, smoked goat’s cheese, almond</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">char-grilledmarketgreens, preservedlemon, shallotoil</td>
              <td>$10</td>
            </tr>
            <tr>
              <td style="width:70%">torn house pane sciocco, olive oil, smoked salt </td>
              <td>$6</td>
            </tr>
          </table>
          </br>
          <table class="table">
            <tr>
              <th style="width:70%">Brick Oven Pizza</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%">GARLIC FLAT BREAD</br>confit garlic | mozzarella | rosemary | smoked salt</td>
              <td>$14</td>
            </tr>
            <tr>
              <td style="width:70%">MARGHERITA</br>tomato | smoked mozzarella | basil</td>
              <td>$18</td>
            </tr>
            <tr>
              <td style="width:70%">PEPPERONI</br>garlic | chilli | oven-dried tomato | mozzarella | basil oil</td>
              <td>$22</td>
            </tr>
            <tr>
              <td style="width:70%">THE REUBEN</br>smoked brisket pastrami | bacon braised cabbage | garlic | mustard mayo | dill pickle | chive</td>
              <td>$25</td>
            </tr>
            <tr>
              <td style="width:70%">THE VIKING</br>butternut pumpkin | danish viking blue cheese | spinach | green olive | sage</td>
              <td>$21</td>
            </tr>
            <tr>
              <td style="width:70%">BLACK SHEEP</br>pulled lamb | beetroot | smoked goats cheese | onion | mustard | mint</td>
              <td>$23</td>
            </tr>
            <tr>
              <td style="width:70%">THE MATADOR</br>prawns | chorizo | tomato | sherry onion | manchego | coriander</td>
              <td>$26</td>
            </tr>
            <tr>
              <td style="width:70%">THE DRUNKEN PIG</br>slow cooked pork | bacon | pepperoni | spicy bourbon bbq sauce | mozzarella | dill pickle</td>
              <td>$25</td>
            </tr>
            <tr>
              <td style="width:70%"><i>Any pizza gluten free</i></td>
              <td><i>add $3.5</i></td>
            </tr>
          </table>
          </br>
          <table class="table">
            <tr>
              <th style="width:70%">Dessert</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%">MASCARPONE PANNA COTTA</br>lemon myrtle curd, Italian meringue, pistachio dust</td>
              <td>$14</td>
            </tr>
            <tr>
              <td style="width:70%">THE BROKEN BEE-HIVE</br>‘bee one third’ & house honeycomb, lavender milk gel, dark chocolate ganache, beetroot, soil</td>
              <td>$16</td>
            </tr>
            <tr>
              <td style="width:70%">NOT YOUR MUM’S STRAWBERRIES & CREAM</br>Stanthorpe strawberries, meander valley clotted cream, basil, rose, freeze dried balsamic, house marshmellow</td>
              <td>$15</td>
            </tr>
            <tr>
              <td style="width:70%">THE WOODEN CHEESE BOARD</br>Our weekly selection of Australian cheeses with accompaniments & house lavosh</br><i>Waiter will advise</i></td>
              <td>$21</td>
            </tr>
            <tr>
              <th style="width:70%">To Accompany</th>
              <th></th>
            </tr>
            <tr>
              <td style="width:70%">Vasse Felix Cane Cut Semillon `13,</br>Margaret River WA</td>
              <td>$11</td>
            </tr>
            <tr>
              <td style="width:70%">Seppeltsfield Para Grand Tawny NV,</br>Barossa Valley SA</td>
              <td>$9</td>
            </tr>
            <tr>
              <td style="width:70%">Sottosopra Vino ed Amarene, Abruzzo ITA,</br>South Eastern AUS</td>
              <td>$15</td>
            </tr>
          </table>
          <%= link_to 'Download Our Menu (PDF)', menu_download_url, class: "btn btn-secondary btn-lg", style: "font-style:italic", alt: "", align: "right" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center">Kids Menu</h2>
        <hr>
        <hr class="visible-xs">
        <p>
          </i>Don't you hate kids menus filled with junk food?
          </br>
          </br>
          We have done our very best to satisfy the little'ns and leave you with a clear conscience.
          </br>
          </br>
          (Available until 7:30 PM)
          </i>
        </p>
        <%= link_to 'Kids Menu (PDF)', menu_kids_url, class: "btn btn-secondary btn-lg", style: "font-style:italic", alt: "", align: "right" %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="container" style="padding-left:0;padding-right:0;">
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" style="padding:10px;padding-top:5px">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/partials/_navbar.html.erb
<!-- Navigation -->
<head>
  <title>Wooden Horse Restaurant & Bar</title>
</head>
<span itemscope itemtype="http://schema.org/Restaurant">
<div class="container">
<div class="row">
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
      <a class="navbar-brand" href>Wooden Horse</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="hidden-xs">
      <%=image_tag 'logoblackontransparent.png', class: "center-block", style: "opacity: 0.65; width:40%; height: 40%;"%>
        <hr style="margin-top:0px; margin-bottom:5px">
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%=link_to "Home", root_path, style: "padding:12px" %>
        </li>
        <li>
          <%=link_to "About", about_path, style: "padding:12px" %>
        </li>
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" style="padding:12px" aria-haspopup="true" aria-expanded="false">Menus <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%=link_to "Food", menu_path, style: "padding:12px", itemprop: "menu" %>
            </li>
            <li>
              <%=link_to "Drink", drink_path, style: "padding:12px" %>
            </li>
          </ul>
        </li>
        <li>
          <%=link_to "Functions", functions_path, style: "padding:12px" %>
        </li>
        <li>
          <%=link_to "Contact", new_contact_path, style: "padding:12px" %>
        </li>
        <li>
          <%=link_to "Book Now", book_path, style: "padding:12px" %>
        </li>
        <li>
          <%=link_to "Gallery", gallery_path, style: "padding:12px" %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  <!-- /.container -->
  </nav>
</div>
</div>